### ISSUE TITLE
Alt+r locks main windows for several seconds

### ISSUE THREAD

**Issue by diversys** [adamfowleruk/Paladin#345]
Alt+r runs an app (Paladin im my case) changes statusbar text to "Updating dependencies" and locks main windows for several seconds so its content doesn't refresh if I move another window above Paladin project window.

**Comment by adamfowleruk** [comment]
Interesting. Builds shouldn't lock the UI.

**Comment by adamfowleruk** [comment]
Tested in the latest develop branch. No longer happens. I did fix a build time draw issue that was similar to this, so perhaps I've also fixed this issue. Closing for now. Please retest on the next release.

**Comment by diversys** [comment]
I can still reproduce it by opening Paladin.pld and selecting Build->Update dependencies.
